### ISSUE TITLE
Servidores Águia Pescadora

### ISSUE THREAD

**Issue by fititnt** [fititnt/cplp-aiops#5]
(Adicionado em 2019-06-22 16:48 BRT) Temos um projeto dedicado para o Águia Pescadora:
- GitHub: <https://github.com/EticaAI/aguia-pescadora>

Pode levar no mínimo semanas para que issues pertinentes do fititnt/cplp-aiops sejam atualizados, visto que minha preocupação é mais ter o PaaS da Etica.AI pronto o quanto antes.

Alguns servidores que não usam Tsuru (e que também eram em torno de 50~100% menos custo-eficiente em relação aos novos) também estão deixando de serem renovados.

----

- [EticaAI/forum, Cluster Águia Pescadora](https://github.com/EticaAI/forum/issues/82) <sup>Destino em Inglês</sup>
- [EticaAI/forum, label:cluster-aguia-pescadora](https://github.com/EticaAI/forum/issues?utf8=%E2%9C%93&q=label%3Acluster-aguia-pescadora) <sup>Destino em Inglês</sup>

----

No momento temos 2 servidores ativos, chamados de Alpha e Bravo.

> Nota: Alpha, que está na CloudAtCost e tem configurações mais fracas, não tem custos mensais (foi pago uma vez). Bravo é mais poderoso, porém é uma experiência de 3 meses sobre se há demanda de contas SSH gratuitas em servidores comunitários em 2019. **Toda documentação de como preparar os servidores é feita de forma amigável para não especialistas e liberada em licença Domínio Público**.

- **`aguia-pescadora.etica.ai`** (padrão)
    - Atualmente ainda aponta para o `aguia-pescadora-alpha.etica.ai`, sera alterado em breve para o Bravo
- **`aguia-pescadora-alpha.etica.ai`**
    - issue: #17
    - IPv4: **104.167.109.226**
    - IPv6: (sem suporte)
    - Servidor:
        - Virtualizado, KVM
        - Sistema operacional: **Ubuntu Server 18.04.02 LTS**
        - CPU: **2 vCPUs**
        - RAM: **1,5GB**
        - Disco: **30 GB SSD**
        - Rede: 100mbit 
            - (teórica, na pratica em torno de **25mbit**)
            - Sem custo adicional por uso de banda!
    - Datacenter:
        - CloudAtCost
        - Canadá
    - DNS: (Nota: curto para digitação rapida, use o longo em configuração de apps!)
        - Longo: **`aguia-pescadora-alpha.etica.ai`** / 
        - Curto: **`apa.etica.ai`**  /
    - HTTP:
        - **<http://aguia-pescadora-alpha.etica.ai>**
        - **<http://apa.etica.ai>**
- **`aguia-pescadora-bravo.etica.ai`**
    - Pacotes instalados: execute `ajuda` ou acesse <https://aguia-pescadora-bravo.etica.ai/ajuda.html>
    - issue: #16
    - IPv4: **192.99.247.117**
    - IPv6: **2607:5300:201:3100:0:0:0:87fc**
    - Servidor:
        - Virtualizado, KVM
        - Sistema operacional: **Ubuntu Server 18.04.02 LTS**
        - CPU: **2 vCPUs**
        - RAM: **8GB** (7,6G) 
            - Nota: **Swap de 12GB, discos SSDs em RAID**
        - Disco: **80 GB SSD**
        - Rede: **100mbit**
            - Sem custo adicional por uso de banda!
        - Outros detalhes para Nerds: <https://aguia-pescadora-bravo.etica.ai/lshw.html>
    - Datacenter:
    - Datacenter:
        - OVH
        - Canadá, Beauharnois, Quebec
    - DNS: (Nota: curto para digitação rapida, use o longo em configuração de apps!)
        - Longo: **`aguia-pescadora-bravo.etica.ai`** / 
        - Curto: **`apb.etica.ai`**  /
    - HTTPS:
        - **<https://aguia-pescadora-bravo.etica.ai>**
        - **<https://apb.etica.ai>**
---

Veja também:

- [Nota em grupo de Facebook: Do zero ao seu perfil profissional no GitHub usando apenas Smartphone Android e internet móvel](https://www.facebook.com/notes/liga%C3%A7%C3%A3o-africa-brasil-programa%C3%A7%C3%A3o-e-inform%C3%A1tica/do-zero-ao-seu-perfil-profissional-no-github-usando-apenas-smartphone-android-e-/296318204621307/)
- [EticaAI/eticaai-shell-scripts/issues/1: Basic commands for the article draft related to use git/GitHub from scratch using a Smarphone with Android 5.0+ & Termux #1](https://github.com/EticaAI/eticaai-shell-scripts/issues/1)

---

Alguns colegas e eu e que há semanas ou meses já estávamos interagindo a respeito de como usar smartphones para desenvolvimento de software criamos um grupo extra-oficial (aka com tom mais criativo) para centralizar lá algumas discussões sobre testes com aplicativos de Android e outras formas de uso.

Entre outros motivos, Android 5.0+ tem disponível um emulador de terminal chamado Termux. E, nossa, ele é bem amigável. Algumas coisas é mais fácil converter scripts que eu já uso em clientes da minha empresa do que o trabalho que eu teria para converter em alguma distribuição de servidor que não fosse baseada em Debian ou CentOS.

Porém um dos problemas aqui é como otimizar para Android < 5.0 sem ter que fazer root nos celulares. Tive diversas discussões sobre isso em diversos lugares em posts do Facebook e conversas privadas, porém nesse momento (até porque é algo mais fácil pelo conhecimento prévio que eu tenho, e pela falta de pessoal) pode fazer mais sentido considerar alternativa de certas tarefas poderem ser feitas remotamente, mesmo que isso implicasse em dar servidores sem custos para pessoas interessadas.

Esse issue aqui é um primeiro teste experimental dessa abordagem.

---
### Edição 1:
- Adicionado referencias a **`aguia-pescadora-alpha.etica.ai`** e **`aguia-pescadora-bravo.etica.ai`**

### Edição 2:
- Adicionado introdução antes da listagem das especificações de Alpha e Bravo
- **`aguia-pescadora-bravo.etica.ai`**: Links de HTTP para HTTPS
- **`aguia-pescadora-bravo.etica.ai`**: aviso sobre swap de 12GB, discos SSDs em RAID

### Edição 3:
- Adicionado os links
    - [EticaAI/forum, Cluster Águia Pescadora](https://github.com/EticaAI/forum/issues/82) <sup>Destino em Inglês</sup>
    - [EticaAI/forum, label:cluster-aguia-pescadora](https://github.com/EticaAI/forum/issues?utf8=%E2%9C%93&q=label%3Acluster-aguia-pescadora) <sup>Destino em Inglês</sup>

### Edição 4
- Adicionado referência de que agora temos um projeto dedicado para o Águia Pescadora no repositório do GitHub <https://github.com/EticaAI/aguia-pescadora>

**Comment by fititnt** [comment]
Durante a atualização do 16.04.02 para o 18.04.01, estou tendo alguns alertas como este

```sh
(...)

update-initramfs: Generating /boot/initrd.img-4.4.0-148-generic
W: initramfs-tools configuration sets RESUME=UUID=c9f61b59-95aa-45ab-ae18-ee968312edc4
W: but no matching swap device is available.
I: The initramfs will attempt to resume from /dev/sda2
I: (UUID=9c03df07-1ce4-4c8c-a4d9-8a84db066941)
I: Set the RESUME variable to override this.
update-initramfs: Generating /boot/initrd.img-4.4.0-62-generic
W: initramfs-tools configuration sets RESUME=UUID=c9f61b59-95aa-45ab-ae18-ee968312edc4
W: but no matching swap device is available.
I: The initramfs will attempt to resume from /dev/sda2
I: (UUID=9c03df07-1ce4-4c8c-a4d9-8a84db066941)
I: Set the RESUME variable to override this.

(...)
```

Alguns links sobre o tema

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860403
- https://askubuntu.com/questions/1013830/slow-boot-long-kernel-load-time-due-to-wrong-resume-device

**Comment by fititnt** [comment]
Comando `ajuda` atual:

![Captura de tela de 2019-05-16 05-33-49](https://user-images.githubusercontent.com/812299/57839011-350a9400-779c-11e9-8349-0b8c0c05e8f5.png)

**Comment by fititnt** [comment]
Considerações sobre ter quotas de uso de disco por usuário a nivel de kernel

- https://www.digitalocean.com/community/tutorials/how-to-set-filesystem-quotas-on-ubuntu-18-04

E também sobre o que os usuários fazem com os arquivos deles, veja

- https://github.com/google/skicka
- https://github.com/dropbox/dbxcli
- https://github.com/borgbackup/borg

**Comment by fititnt** [comment]
Nota pra mim mesmo: problema que falei no comentário https://github.com/fititnt/cplp-aiops/issues/5#issuecomment-492898445 que eu já sabia ser publicamente conhecido de que poderia deixar lento chegou a dar um susto de eu achar que tinha perdido a VM.

Ela chegou a voltar depois de outro reboot, mas no meio tempo eu resolvi dar uma olhada pra continuar essa aqui na OVH em uma VPS já com mais espaço. Então é possível que em vez de deixar uma VPS menor por tempo indeterminado na cloudatcost, eu crie uma na OVH com dinheiro pago por mim mesmo e deixe rodando por uns 3 meses e veja se pelo menos vai chegar a ter uso real das pessoas a ponto de valer a pena permanecer ser usada.

Ou seja, se for para manter um plano de na OVH de:

> VPS SSD 3
> OpenStack KVM
> 2 vCore(s)
> From 2 GHz
> 8 GB RAM
> 80 GB SSDNEW
> Local RAID
> $14.99/month

diferente da atual (2 vCPUs, 1,5GB RAM, 30GB SSD (CloudAtCost)) que fazia parte de pacote que paguei uma vez pra uso até a CloudAtCost fechar e não me importaria de deixar ligado o tempo todo mesmo com baixo uso, se a gente for manter essa aqui ligada, nem digo ajuda pra pagar ela (isso eu faço), mas ajuda pra documentar como pessoal pode usar ela de graça seria muito bem vinda.

Por mais que os servidores da OVH não sejam caros, ainda assim eu não gosto da ideia de deixar uma VPS de 8GB de ram não sendo usada.

**Comment by fititnt** [comment]
DNSs alterados na cloudflare da @EticaAI

![Captura de tela de 2019-05-17 22-27-49](https://user-images.githubusercontent.com/812299/57962875-081cc500-78f3-11e9-9f02-5a4024ee1a0c.png)

**Comment by fititnt** [comment]
Algo a ser considerado: Instalar Multi-Factor Authentication como potencial alternativa para usuários.

- <https://www.digitalocean.com/community/tutorials/how-to-configure-multi-factor-authentication-on-ubuntu-18-04>

**Comment by fititnt** [comment]
Dependendo da forma como alguns binários são instalados (exemplo atual: #23 Go Lang, com Snap) o path dos executáveis não é instalado para todo mundo.

Aqui tem algumas alternativas

- https://askubuntu.com/questions/261760/setting-global-environment-variable-for-everyone/1122929#1122929
- https://askubuntu.com/questions/247738/why-is-etc-profile-not-invoked-for-non-login-shells/247769#247769

**Comment by fititnt** [comment]
Pessoal, uma nota nota aqui de potencial alteração (e justificativa de porque, mesmo antes dos três meses, algumas VPSs serão trocadas por outras:

**O principal motivo é que encontrei um provedor _ainda_ mais custo benefício do que as VPSs da OVH.** E não estou falando de apenas 20~40% mais barato, significativamente mais barato ao ponto de valer a pena trocar as VPS que estão na OVH para um datacenter novo, tendo em torno de pelo menos o dobro de todas as configurações em relação ao atual (no caso de disco SSD, chega a ser 5 vezes mais!).

Comparem as especificações da Bravo (OVH, Canada) e do servidor que estou testando na Contabo (Alemanha).

- Servidor Águia Pescadora Bravo #16 
    - [2vCPU / 8GB / 80GB]
        - Benchmarks: [logbook/aguia-pescadora-bravo-benchmarks.sh](https://github.com/fititnt/cplp-aiops/blob/master/logbook/aguia-pescadora-bravo-benchmarks.sh)
    - **15 USD**
    - **58,10 BRL**
- Servidor Águia Pescadora Delta #63 
    - [6vCPU / 16GB / 400GB] 
        - Benchmarks: [aguia-pescadora-delta-benchmarks.sh](https://github.com/fititnt/cplp-aiops/blob/master/logbook/aguia-pescadora-delta-benchmarks.sh)
    - **8,99 EUR** (Setup: 4,99 EUR)
    - **39,49 BRL** (Setup: 21,81 BRL)

Para vocês terem ideia, pelo preço da Bravo, a gente _quase_ consegue uma VM na Contabo de 8vCPUs, 30 GB de RAM e 800GB SSD. Eu não cheguei a pegar essa além dessa Delta, possivelmente teriamos mais 2 VMs menores possíveis no novo datacenter (que, diga-se de passagem, significa 4 vCPUs 8 GB de RAM e 200 GB de disco SSD) para poder substituir também as **Servidores em cluster Elefante Bornéu #45**.

Note que com esses preços novos, acredito que podemos expandir além desses 3 meses de período de testes. Talvez se tiver pouco uso, em vez de manter a Delta + duas menores, eu apenas desative as menores e fique permanentemente com a Delta.



![Captura de tela de 2019-06-10 00-58-46](https://user-images.githubusercontent.com/812299/59415715-67f37800-8d9a-11e9-802a-9db39bec7315.png)

**Comment by fititnt** [comment]
TL:DR:  **vamos preferir fazer acesso via conteiners em detrimento de acesso SSH direto nas VMs das Aguia Pescadoras mais novas, e o acesso por usuários (mesmo os administrativos) tenderá a ser principalmente via Tsuru #59**

---


Outro ponto de mudança muito significativa sobre os servidores Águia Pescadora, talvez até maior do que desativar um nó por outro mais potente e mais barato: **vamos preferir fazer acesso via conteiners em detrimento de acesso SSH**.

Um dos motivos de evitar o uso de **Docker #61** (e também que a ideia de Aguia Pescadora seria tentar replicar experiência com as **VPS mamba [2vCPU / 1GB / 20GB] https://github.com/EticaAI/forum/issues/72** era de que poderia ser mais simples para usuários finais não ter que aprender Docker e poder fazer acesso SSH numa VM inteira. Outra vantagem adicional era de que isso, teoricamente, permitiria usar VPSs mais baratas, com discos menores. Mas isso traz alguns problemas adicionais, como a complexidade de gerenciar, por exemplo, o https://github.com/fititnt/cplp-aiops/issues/27. Outro ponto é que uma das ideias mais fantásticas que estavam tendo para usar a Bravo (inclusive tem MVP disso) era de um CompileBot para ser integrado ao Facebook Mensager. Porém mesmo tentando criar um usuário e senha separado, tentando técnicas de jail, e etc, teoricamente não conseguiria o nível de isolamento ideal.

Tem outros motivos que eu poderia citar, mas com os preços atuais (em especial de discos SSDs bem mais generosos) algumas otimizações para permitir ter servidores de baixo custo ficam menos relevantes. E mesmo que tivéssemos dinheiro à vontade, o Tsuro permite um nivel de simplificação que permite ser a estratégia mais padrão para usuários, mesmo que isso não abandone completamente ainda termos alguma alternativa (isto para número menor de usuários) de acesso SSH diretamente.

Tem outros motivos, mas na correria que estou (até para encerrar a Bravo antes de terminar um mês) creio que isso que posso falar rapidinho. Lembrando que será feito backup completo dela (além de toda documentação de como reconstruir do zero a Bravo). Então usuários (mesmo que demorem semanas) não teriam perdido dados.

**Comment by Uriel29** [comment]
Muito bom!

**Comment by fititnt** [comment]
Temos um projeto dedicado para o Águia Pescadora:
- GitHub: <https://github.com/EticaAI/aguia-pescadora>

Pode levar no mínimo semanas para que issues pertinentes do fititnt/cplp-aiops sejam atualizados, visto que minha preocupação é mais ter o PaaS da Etica.AI pronto o quanto antes.

Alguns servidores que não usam Tsuru (e que também eram em torno de 50~100% menos custo-eficiente em relação aos novos) também estão deixando de serem renovados.

**Comment by fititnt** [comment]
See https://github.com/EticaAI/forum/issues/92#issuecomment-1272738523
